server:
  port: 8083
spring:
  application:
    name: guest
  data:
    mongodb:
      uri: mongodb://mongo:27017/guests
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
discount:
  onePercentAmount: 3000
  maxPercent: 20